messages:
  toggle-on:
    - '<gray>Toggled</gray> <green>On</green><gray> staff mode'
  toggle-off:
    - '<gray>Toggled</gray> <red>Off</red><gray> staff mode'
actionbar:
  enable: true
  bar: '<green>You are currently in staff mode</green>'
commands:
  off:
    - 'fly off'
    - 'v off'
    - 'gm 0'
  on:
    - ''
